version: "3.8"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 7000:80
    caddy:
      image: caddy
      ports:
        - 80:80
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
